import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Container from "@/components/container";
import "./globals.css";


const pangram = localFont({
  src: "./fonts/PPPangramSansRounded-Medium.otf",
});

export const metadata: Metadata = {
  title: "iLevel Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pangram.className} font-normal antialiased`}>
        <Navbar />
        <main className="flex flex-col">
          <Container>{children}</Container>
        </main>
        <Footer />
      </body>
    </html>
  );
}
