import Footer from "@/components/footer";
import Navbar from "@/components/header";
import Container from "@/components/container";
import MetaPixel from "@/components/meta-pixel"; // подключение скрипта
import localFont from "next/font/local";
import { FC, ReactNode } from "react";
import "./globals.css";

const pangram = localFont({
  src: "./fonts/PPPangramSansRounded-Medium.otf",
});

type RootLayoutProps = {
  children: ReactNode;
};

export const metadata = {
  title: "iLevel Shop",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${pangram.className} font-normal antialiased`}>
        <div>
          <Navbar />
          <main className="flex flex-col">
            <Container>{children}</Container>
          </main>
          <Footer />
        </div>

        {/* Meta Pixel */}
        <MetaPixel />
      </body>
    </html>
  );
};

export default RootLayout;
